Extend build with transport
conda-forge/dftbplus-feedstock pull request #12
Opened 2021-02-01 22:11 UTC by aradi

Also use the customized source archive instead of GitHubs
automatically generated one to ensure that the RELEASE file is
contained.

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X ] Ensured the license file is being packaged.

2021-02-01 22:11 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2021-02-01 22:13 UTC, aradi commented
@conda-forge-admin please rerender

2021-02-01 22:22 UTC, aradi commented
@conda-forge-admin please rerender

2021-02-01 23:27 UTC, awvwgk commented
CMake's detection for MPI is currently broken in mpich 3.4.x (https://github.com/conda-forge/mpich-feedstock/issues/56).

Pinning mpich to not 3.4.x in host seems to work for now, but is quite ugly:

```yaml
  host:
    - {{ mpi }}  # [mpi != "nompi"]
    - mpich !=3.4  # [mpi == "mpich"]
```

I would recommend to wait for upstream to fix this issue instead of messing with the host dependencies.

2021-02-01 23:31 UTC, aradi commented
@awvwgk Do you have by any chance clue, why the OSX with MPICH fails? I can not see, why any of my changes should have caused this failure... (I guess, OSX and me are not really compatible for some reasons :wink: )

2021-02-01 23:47 UTC, aradi commented
Makes sense, the PR is not too urgent.

2021-02-07 15:04 UTC, awvwgk commented
@conda-forge-admin, please restart CI

2021-02-12 12:20 UTC, awvwgk commented
@aradi what is the status on this patch? The CI is passing with the MPICH fix so we could move this forward now.

2021-02-12 12:21 UTC, awvwgk commented on recipe/meta.yaml
> +    - libnegf * {{ mpi_prefix }}_*
The correct `libnegf` version is picked automatically for non-MPI builds, constraints only apply for MPI builds:
```suggestion
    - libnegf
    - libnegf * {{ mpi_prefix }}_*  # [mpi != "nompi"]
```

2021-02-12 13:18 UTC, awvwgk requested changes
Also `libnegf` should be pinned in the run dependencies correctly.

2021-02-28 12:05 UTC, awvwgk commented
@aradi What is the status on this PR?

2021-02-28 12:14 UTC, awvwgk approved these changes

2021-03-04 12:11 UTC, merged